////////////////////////////////////////////////////////////
//  DO NOT DIRECTLY EDIT THIS FILE!!!
//  This file is generated by the updateapi custom django command.
//  Unless functionality needs to be added, the best way to have
//  changes in here is to modify the openapi definition in
//  endpoints.openapi.yaml
////////////////////////////////////////////////////////////

/* eslint-disable @typescript-eslint/no-unused-vars */
import { Result, Options, useGet } from "./helpers";
import { DateTime } from "../shared/dateTime";
import { Duration } from "../shared/duration";

import {
  parameterMarshalers,
  unmarshalers,
  Four04Reply,
  RunOperationReply,
  RunOperation,
  PartTo,
  TaskDefinition,
  RunState,
  PartToId,
  RunStateId,
  TaskDefinitionId,
} from "./sharedschemas";

/* eslint-enable @typescript-eslint/no-unused-vars */

export type ParttoGet200Body = {
  name: string;
  workDuration?: Duration | undefined;
  clockDuration?: Duration | undefined;
  tasks: Array<TaskDefinitionId>;
};

type Wire200Body = {
  name: string;
  workDuration?: number | undefined;
  clockDuration?: number | undefined;
  tasks: Array<TaskDefinitionId>;
};

export type ParttoGetArguments = { partTo: PartToId };

interface ExternalMappers {
  [status: string]: (arg: Wire200Body) => ParttoGet200Body;

  200: (arg: Wire200Body) => ParttoGet200Body;
}

export type ParttoGetResult = Result<ParttoGet200Body>;

export const useParttoGet: (
  args: ParttoGetArguments,
  options?: Options,
) => ParttoGetResult = ({ partTo }, options) =>
  useGet<Wire200Body, ParttoGet200Body, ExternalMappers>(
    "/api/partto/",
    [
      {
        name: "partTo",
        value: parameterMarshalers.required["PartToId"](partTo),
      },
    ],
    {
      200: (body: Wire200Body) => ({
        name: unmarshalers.required["string"](body.name),
        workDuration: unmarshalers.unrequired["duration"](body.workDuration),
        clockDuration: unmarshalers.unrequired["duration"](body.clockDuration),
        tasks: body.tasks.map((value) =>
          unmarshalers.required["TaskDefinitionId"](value),
        ),
      }),
    },
    options,
  );
