////////////////////////////////////////////////////////////
//  DO NOT DIRECTLY EDIT THIS FILE!!!
//  This file is generated by the updateapi custom django command.
//  Unless functionality needs to be added, the best way to have
//  changes in here is to modify the openapi definition in
//  endpoints.openapi.yaml
////////////////////////////////////////////////////////////

/* eslint-disable @typescript-eslint/no-unused-vars */
import { Result, DateTime, Duration, useGet } from "./helpers";

import {
  parameterMarshalers,
  unmarshalers,
  PartTo,
  TaskDefinition,
  RunState,
  RunStateId,
  TaskDefinitionId,
  PartToId,
} from "./sharedschemas";

/* eslint-enable @typescript-eslint/no-unused-vars */

export interface ParttoGet200Body {
  name: string;
  tasks: Array<TaskDefinitionId>;
}

interface Wire200Body {
  name: string;
  tasks: Array<TaskDefinitionId>;
}

export interface ParttoGetArguments {
  id: PartToId;
}

interface ExternalMappers {
  [status: string]: (arg: Wire200Body) => ParttoGet200Body;

  200: (arg: Wire200Body) => ParttoGet200Body;
}

export type ParttoGetResult = Result<ParttoGet200Body>;

export const useParttoGet: (args: ParttoGetArguments) => ParttoGetResult = ({
  id,
}) =>
  useGet<Wire200Body, ParttoGet200Body, ExternalMappers>(
    "/api/partto/",
    [{ name: "id", value: parameterMarshalers.required["PartToId"](id) }],
    {
      200: (body: Wire200Body) => ({
        name: unmarshalers.required["string"](body.name),
        tasks: body.tasks.map((value) =>
          unmarshalers.required["TaskDefinitionId"](value),
        ),
      }),
    },
  );
