////////////////////////////////////////////////////////////
//  DO NOT DIRECTLY EDIT THIS FILE!!!
//  This file is generated by the updateapi custom django command.
//  Unless functionality needs to be added, the best way to have
//  changes in here is to modify the openapi definition in
//  endpoints.openapi.yaml
////////////////////////////////////////////////////////////

/* eslint-disable @typescript-eslint/no-unused-vars */
import { PostArgumentsBase, DateTime, Duration, doPost } from "./helpers";

import {
  parameterMarshalers,
  bodyMarshalers,
  unmarshalers,
  Four04Reply,
  RunOperationReply,
  RunOperation,
  PartTo,
  TaskDefinition,
  RunState,
  PartToId,
  RunStateId,
  TaskDefinitionId,
} from "./sharedschemas";
/* eslint-enable @typescript-eslint/no-unused-vars */

export type RunstagePostBody = {
  runState?: RunStateId | undefined;
  partTos: Array<PartToId>;
};

type WireBody = { runState?: RunStateId | undefined; partTos: Array<PartToId> };

export type RunstagePost200Body = { runState: RunStateId };

type Wire200Body = { runState: RunStateId };

interface ExternalMappers {
  [status: string]: (arg: Wire200Body) => RunstagePost200Body;

  200: (arg: Wire200Body) => RunstagePost200Body;
}

interface ExternalHandlers {
  [status: string]: (arg: RunstagePost200Body) => void;

  200: (arg: RunstagePost200Body) => void;
}

export interface JobPostArguments extends PostArgumentsBase<RunstagePostBody> {
  on200: (arg: RunstagePost200Body) => void;
}

export const doRunstagePost = async ({
  body,

  on200,
}: JobPostArguments) =>
  await doPost<
    WireBody,
    Wire200Body,
    RunstagePost200Body,
    ExternalMappers,
    ExternalHandlers
  >(
    "/api/run/stage",
    {
      runState: bodyMarshalers.unrequired["RunStateId"](body.runState),
      partTos: body.partTos.map((value) =>
        bodyMarshalers.required["PartToId"](value),
      ),
    },
    {
      200: (body: Wire200Body) => ({
        runState: unmarshalers.required["RunStateId"](body.runState),
      }),
    },
    {
      200: on200,
    },
  );
