////////////////////////////////////////////////////////////
//  DO NOT DIRECTLY EDIT THIS FILE!!!
//  This file is generated by the updateapi custom django command.
//  Unless functionality needs to be added, the best way to have
//  changes in here is to modify the openapi definition in
//  endpoints.openapi.yaml
////////////////////////////////////////////////////////////

/* eslint-disable @typescript-eslint/no-unused-vars */
import { Result, Options, useGet } from "./helpers";
import { DateTime } from "../shared/dateTime";
import { Duration } from "../shared/duration";

import {
  parameterMarshalers,
  unmarshalers,
  Four04Reply,
  RunOperationReply,
  RunOperation,
  PartTo,
  TaskDefinition,
  RunState,
  PartToId,
  RunStateId,
  TaskDefinitionId,
} from "./sharedschemas";

/* eslint-enable @typescript-eslint/no-unused-vars */

export type VersionGet200Body = {
  major: number;
  minor: number;
  fix: number;
  build: number;
  variant: string;
  timestamp: DateTime;
};

type Wire200Body = {
  major: number;
  minor: number;
  fix: number;
  build: number;
  variant: string;
  timestamp: string;
};

interface ExternalMappers {
  [status: string]: (arg: Wire200Body) => VersionGet200Body;

  200: (arg: Wire200Body) => VersionGet200Body;
}

export type VersionGetResult = Result<VersionGet200Body>;

export const useVersionGet: (options?: Options) => VersionGetResult = (
  options,
) =>
  useGet<Wire200Body, VersionGet200Body, ExternalMappers>(
    "/api/applicationVersion/",
    [],
    {
      200: (body: Wire200Body) => ({
        major: unmarshalers.required["number"](body.major),
        minor: unmarshalers.required["number"](body.minor),
        fix: unmarshalers.required["number"](body.fix),
        build: unmarshalers.required["number"](body.build),
        variant: unmarshalers.required["string"](body.variant),
        timestamp: unmarshalers.required["date-time"](body.timestamp),
      }),
    },
    options,
  );
