[part_to]
name = "Frozen Green Beans"
depends = ["drain_and_serve"]

[drain_and_serve]
tools = ["strainer"]
description = "drain and serve beans"
duration = "30 seconds"
depends = ["re_boil_water"]

[re_boil_water]
description = "get water boiling again"
duration = "2 minutes"
engagement = 2
depends = ["boil_beans_in_pot"]

[boil_water]
tools = ["large pot"]
description = "boil water in large pot for beans"
duration = "9 minutes"
engagement = 2

[boil_beans_in_pot]
ingredients = ["frozen green beans"]
description = "put and leave beans in boiling water"
duration = "4 minutes"
engagement = 5
depends = ["boil_water"]
