[part_to]
name = "Baked Beans (Easy)"
depends = ["let_cool"]

[remove_beans_from_oven]
duration = "10 seconds"
description = "remove beans from oven"
depends = ["bake_beans"]

[let_cool]
duration = "5 minutes"
description = "remove pan from oven and let stand for 5 minutes"
depends = ["remove_beans_from_oven"]
engagement = 5

[bake_beans]
description = "bake to desired consistency"
duration = "2 hours 30 minutes"
engagement = 2
depends = ["heat_oven", "assemble_beans"]

[cook_bacon]
duration = "20 minutes"
description = "cook bacon to slightly rare"
depends = ["put_bacon_in_oven"]
engagement = 3

[put_bacon_in_oven]
duration = "2 minutes"
description = "put 10 slices of bacon on pan and put in oven"
tools = ["flatish baking pan"]
ingredients = ["bacon, 10 slices"]
depends = ["heat_oven"]

[gather_ingredients]
description = "gather and combine 54 oz canned pork and beans, 2 tsp dry mustard, 2/3 cup brown sugar, 1/4 cup cider vinegar, 4 tbs ketchup, & 1/4 cup molasses"
ingredients = ["pork and beans, 54 oz canned", "dry mustard, 2 tsp", "brown sugar, 2/3 cup", "cider vinegar, 1/4 cup", "ketchup, 4 tbs", "molasses, 1/4 cup"]
duration = "3 minutes"

[dice_veggies]
duration = "2 minute"
description = "dice half of a green pepper and a whole yellow onion and combine aside"
ingredients = ["green pepper, 1/2", "yellow onion, 1"]

[get_pan]
duration = "1 minute"
description = "get pan and put 2 tbs butter in it"
ingredients = ["butter, 2 tbs"]

[heat_pan]
duration = "2 minutes 30 seconds"
description = "heat pan to medium heat"
engagement = 1
depends = ["get_pan"]

[saute_veggies]
duration = "5 minutes"
description = "saute diced green peppers and onion"
engagement = 10
# it'd be good to test here if dicing veggies happens before this if dicing takes longer than heating
depends = ["heat_pan", "dice_veggies"]

[simmer_beans]
duration = "90 seconds"
description = "simmer bean mixture a minute or so"
depends = ["gather_ingredients", "saute_veggies"]

[assemble_beans]
duration = "30 seconds"
description = "pour bean mixture in 3 quart baking pan and layout cooked bacon on top"
depends = ["grease_bean_pan", "cook_bacon", "simmer_beans"]

[grease_bean_pan]
duration = "45 seconds"
description = "grease 3 quart baking pan"
tools = ["3 qt baking pan"]

[heat_oven]
duration = "15 minutes"
description = "Heat Oven to 325 degrees"
engagement = 1




