############################################################
#  DO NOT DIRECTLY EDIT THIS FILE!!!
#  This file is generated by the updateapi custom django command.
#  Unless functionality needs to be added, the best way to have
#  changes in here is to modify the openapi definition in
#  endpoints.openapi.yaml
############################################################

import parttobe.openapiviews.helpers as helpers
import collections

arguments = collections.namedtuple(
    "RunPostArgumentsType",
    [
        "jobs",
        "respond_200",
    ],
)

responders = {
    "200": helpers.get_body_constructor("run:post", "200"),
}
