[part_to]
name = "Apple Crisp"
depends = ["Bake"]

['Heat']
duration = "8 minutes"
description = "Preheat oven to 350 degrees"
tools = ["Oven"]
engagement = 2

['Grease']
duration = "1 minute"
description = "Grease a deep dish pie plate or large baking dish cooking spray and set aside"
tools = ["Deep dish pie plate or large baking dish"]
ingredients=["cooking spray"]

['Cut']
duration = "4 minutes"
description = "Slice apples in put in a bowl large enough to mix a little with it"
ingredients=["5 cups (3ish apples)"]

['Mix']
duration = "3 minutes"
description = "Combine sliced apples with other ingredients"
ingredients=["1/2 cup sugar", "1/2 tsp cinnamon", "1 tsp vanilla extract"]
depends=["Cut"]

['Pour']
duration = "1 minute"
description = "Pour the apple mixture into the baking dish"
depends=['Grease', 'Mix']

['Crumble']
duration = "4 minutes"
description = "Combine crumble components in a medium dish and stir"
ingredients=["1/2 cup flour ", "1/3 cup oats", "2/3 cup brown sugar", "1/4 tsp salt", "1/2 tsp cinnamon"]

['Melt']
duration = "2 minute"
description = "Melt butter in microwave and stir into crumble until well coated and crumbly"
tools = ["Microwave"]
engagement = 44
ingredients=["1/4 cup (1/2 stick) butter"]
depends=['Crumble', 'Pour']

['Bake']
duration = "55 minutes"
description = "bake in 350 degree oven for 45-60 minutes until fruit is soft and topping is golden brown"
engagement = 2
depends=['Sprinkle', 'Heat']

['Sprinkle']
duration = "1 minute"
description = "Sprinkle crumble evenly over fruit in baking dish"
depends=['Melt']

