[part_to]
name = "Broccoli Crunch Salad"
depends = ["mix"]


[boil]
duration = "10 minutes"
description = "boil water for farro"
tools = []
depends = []
engagement = 4


[farro]
duration = "20 minutes"
description = "put the farro in the boiling water"
tools = []
depends = ["boil"]
engagement = 4
ingredients = ["enough farro to make a cup"]


[mix]
duration = "1 minute"
description = "remove the baking sheet from the oven and mix into the serving bowl"
depends = ["cook", "dressing"]
ingredients = [ ]



[cook]
duration = "32 minutes"
description = "put baking sheet in heated oven for 30-35 minutes"
tools = []
depends = ["preheat", "cookable"]
engagement = 4
ingredients = [ ]



[preheat]
duration = "8 minutes"
description = "preheat an oven to 400 degrees"
tools = []
depends = []
engagement = 2



[cookable]
duration = "5 minutes"
description = "in a mixing bowl toss: broccoli cut into small florets, drained can of chickpeas, oil, salt, pepper, and garlic pepper - Then spread on a parchment paper lined baking sheet"
ingredients = [ "4 small heads broccoli - cut into small florets", "1 can chickpeas - drained", "1 tablespoon oil", "1 teaspoon salt", "1 teaspoon black pepper", "1 teaspoon garlic pepper" ]


[dressing]
duration = "3 minutes"
description = "combine the ingredients of the dressing in a bowl and mix into the serving bowl"
tools = []
depends = ["other"]
ingredients = [ "1/2 cup olive oil", "1/3 cup balsamic vinegar", "1 teaspoon maple syrup", "2 tablespoon tahini", "1 minced garlic clove", "1 tablespoon soy sauce", "pepper to taste" ]



[other]
duration = "5 minutes"
description = "finely chop the celery and parsley and put it in the serving bowl with 1 cup of salted pistachios and 1 cup of cooked farro"
tools = []
depends = ["farro"]
ingredients = [ "4 stalks celery", "1 bunch parsley", "1 cup shelled pistachios" ]


