[part_to]
name = "Corn on the Cob"
depends = ["Remove from Heat"]

['Wash Corn']
duration = "1 minutes"
description = "wash the corn"
ingredients = ["cobbed corn"]

['Half Cobs']
duration = "2 minutes"
description = "cut partially with kitchen shears to weaken cob middle to break in half"
tools = ["kitchen shears"]
depends = ["Wash Corn"]

['Boil Water']
duration = "8 minutes"
description = "boil water in large pot"
tools = ["large pot"]
engagement = 2

['Boil']
duration = "4 minutes"
description = "put corn in and boil"
engagement = 4
depends = ["Boil Water", "Half Cobs"]

['Remove from Heat']
duration = "20 seconds"
description = "remove from heat"
depends = ["Boil"]
