[part_to]
name = "Squash Roasted"
depends = ["cook2"]

['cut']
duration = "10 minutes"
description = "cut the squash into one inch cubes"
ingredients = ["desired amount of squash"]


['line']
duration = "1 minutes"
description = "line a rimmed baking sheet with parchment paper"
ingredients = []
tools = ['baking sheet']
depends = []


['arrange']
duration = "2 minutes"
description = "arrange squash cubes on rimmed/lined baking sheet"
ingredients = []
tools = []
depends = ['cut', 'line']


['preheat']
duration = "15 minutes"
description = "preheat oven to 400 degrees"
ingredients = []
tools = ['400 degree oven']
engagement = 2
depends = []


['cook1']
duration = "30 minutes"
description = "put in oven and bake for 30 minutes"
ingredients = []
tools = []
engagement = 2
depends = ['preheat', 'arrange']


['stir']
duration = "2 minutes"
description = "pull squash out of oven and flip"
ingredients = []
tools = []
depends = ['cook1']

['cook2']
duration = "30 minutes"
description = "put in oven and bake for 30 minutes or until tender brown and check with fork for correct firmness"
ingredients = []
tools = []
engagement = 2
depends = ['stir']

