# Generated by Django 5.0.3 on 2024-04-21 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parttobe", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="taskdefinition",
            old_name="duration",
            new_name="initial_duration",
        ),
    ]
