# Generated by Django 5.0.3 on 2024-04-28 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "parttobe",
            "0002_rename_duration_taskdefinition_initial_duration",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="PartToTaskDefinition",
        ),
    ]
