# Generated by Django 5.0.3 on 2024-05-18 20:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parttobe", "0003_delete_parttotaskdefinition"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartToRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name="RunPart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started", models.DateTimeField()),
                ("ended", models.DateTimeField(null=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.AddField(
            model_name="partto",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="taskdefinition",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddIndex(
            model_name="partto",
            index=models.Index(fields=["uuid"], name="parttobe_pa_uuid_0afe89_idx"),
        ),
        migrations.AddIndex(
            model_name="taskdefinition",
            index=models.Index(fields=["uuid"], name="parttobe_ta_uuid_a6718b_idx"),
        ),
        migrations.AddIndex(
            model_name="parttorun",
            index=models.Index(fields=["uuid"], name="parttobe_pa_uuid_3d5965_idx"),
        ),
        migrations.AddField(
            model_name="runpart",
            name="part_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="parttobe.partto"
            ),
        ),
        migrations.AddField(
            model_name="runpart",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="parttobe.parttorun"
            ),
        ),
        migrations.AddField(
            model_name="taskstatus",
            name="definition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="parttobe.taskdefinition",
            ),
        ),
        migrations.AddField(
            model_name="taskstatus",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="parttobe.parttorun"
            ),
        ),
        migrations.AddIndex(
            model_name="taskstatus",
            index=models.Index(fields=["uuid"], name="parttobe_ta_uuid_967b41_idx"),
        ),
    ]
