# Generated by Django 5.0.3 on 2024-10-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parttobe", "0005_alter_taskstatus_started_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="runstate",
            name="operation",
            field=models.IntegerField(
                choices=[
                    (1, "Staged"),
                    (2, "Started"),
                    (3, "Completed"),
                    (4, "Voided"),
                ]
            ),
        ),
    ]
