# Generated by Django 5.0.3 on 2024-10-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parttobe", "0006_alter_runstate_operation"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="runstate",
            name="parttobe_ru_uuid_21b900_idx",
        ),
        migrations.AlterField(
            model_name="runstate",
            name="operation",
            field=models.IntegerField(
                choices=[
                    (1, "Staged"),
                    (2, "Started"),
                    (3, "Completed"),
                    (4, "Voided"),
                    (5, "Created"),
                ]
            ),
        ),
        migrations.AddIndex(
            model_name="runstate",
            index=models.Index(
                fields=["uuid", "created"],
                name="parttobe_ru_uuid_5c293e_idx",
            ),
        ),
    ]
