# Generated by Django 5.0.3 on 2024-11-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "parttobe",
            "0007_remove_runstate_parttobe_ru_uuid_21b900_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="runstate",
            name="parttobe_ru_uuid_5c293e_idx",
        ),
        migrations.AddIndex(
            model_name="runstate",
            index=models.Index(
                fields=["uuid", "created", "task"],
                name="parttobe_ru_uuid_0c1b37_idx",
            ),
        ),
    ]
