# Generated by Django 5.0.3 on 2024-12-30 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "parttobe",
            "0008_remove_runstate_parttobe_ru_uuid_5c293e_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskstatus",
            name="run",
        ),
        migrations.RemoveField(
            model_name="runpart",
            name="run",
        ),
        migrations.RemoveField(
            model_name="runpart",
            name="part_to",
        ),
        migrations.AlterUniqueTogether(
            name="taskstatus",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="taskstatus",
            name="definition",
        ),
        migrations.DeleteModel(
            name="PartToRun",
        ),
        migrations.DeleteModel(
            name="RunPart",
        ),
        migrations.DeleteModel(
            name="TaskStatus",
        ),
    ]
