# Generated by Django 5.0.3 on 2025-06-30 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "parttobe",
            "0009_remove_taskstatus_run_remove_runpart_run_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskdefinition",
            name="depended",
        ),
        migrations.CreateModel(
            name="Dependent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "depended",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependent_taskdefinition_depended",
                        to="parttobe.taskdefinition",
                    ),
                ),
                (
                    "dependency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependent_taskdefinition_dependency",
                        to="parttobe.taskdefinition",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["depended"],
                        name="parttobe_de_depende_b98e76_idx",
                    ),
                    models.Index(
                        fields=["dependency"],
                        name="parttobe_de_depende_19adfb_idx",
                    ),
                ],
                "unique_together": {("depended", "dependency")},
            },
        ),
    ]
