# Generated by Django 5.0.3 on 2025-12-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parttobe", "0010_remove_taskdefinition_depended_dependent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskdefinition",
            name="description",
            field=models.CharField(),
        ),
    ]
