openapi: "3.0.0"
servers:
- url: http://testserver/api
info:
  version: 1.0.0
  title: Part To
  license:
    name: MIT
paths:
  /api/job/:
    get:
      summary: Disclose a job definition
      operationId: job:get
      tags:
      - job
      parameters:
      - name: id
        in: query
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '500':
          description: a backend bug
          content:
            '*':
              schema:
                type: string
        '400':
          description: a frontend bug
          content:
            '*':
              schema:
                type: array
                items:
                  type: string
        '200':
          description: Expected response to a valid request
          content:
            '*':
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  name:
                    type: string
                  tasks:
                    type: array
                    items:
                      type: string
                      format: uuid
    post:
      summary: Define a job
      operationId: job:post
      tags:
      - job
      requestBody:
        description: describe job
        content:
          '*':
            schema:
              type: object
              properties:
                part_to:
                  type: object
                  properties:
                    name:
                      type: string
                    depends:
                      type: array
                      items:
                        type: string
                        format: uuid
                tasks:
                  type: array
                  items:
                    $ref: "#/components/schemas/Task"
      responses:
        '500':
          description: a backend bug
          content:
            '*':
              schema:
                type: string
        '400':
          description: a frontend bug
          content:
            '*':
              schema:
                type: array
                items:
                  type: string
        '200':
          description: Expected response to a valid request
          content:
            '*':
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  message:
                    type: string
  /api/run/:
    post:
      summary: Start a run
      operationId: run:post
      tags:
      - run
      requestBody:
        description: List of unique job titles to run
        required: true
        content:
          '*':
            schema:
              type: object
              properties:
                jobs:
                  type: array
                  items:
                    type: string
                    format: uuid
                  minItems: 1
      responses:
        '500':
          description: a backend bug
          content:
            '*':
              schema:
                type: string
        '400':
          description: a frontend bug
          content:
            '*':
              schema:
                type: array
                items:
                  type: string
        '200':
          description: Expected response to a valid request
          content:
            '*':
              schema:
                $ref: "#/components/schemas/RunState"
components:
  schemas:
    Task:
      required:
      - duration
      - description
      - name
      type: object
      properties:
        name:
          type: string
        duration:
          type: string
          format: duration
        description:
          type: string
        depends:
          type: array
          items:
            type: string
        engagement:
          type: number
    RunState:
      required:
      - id
      - report
      - complete
      - duties
      - tasks
      type: object
      properties:
        id:
          type: string
          format: uuid
        report:
          type: string
          format: date-time
        complete:
          type: string
          format: date-time
        duties:
          type: array
          items:
            type: string
            format: uuid
        tasks:
          type: array
          items:
            type: string
            format: uuid
