openapi: "3.0.0"
servers:
- url: http://testserver/api
info:
  version: 1.0.0
  title: Part To
  license:
    name: MIT
paths:
  /api/partto/:
    get:
      summary: Disclose a part to definition
      operationId: partto:get
      tags:
      - partto 
      parameters:
      - name: partTo
        in: query
        required: true
        schema:
          type: string
          format: PartToId
      responses:
        '500':
          description: a backend bug
          content:
            '*':
              schema:
                type: string
        '400':
          description: a frontend bug
          content:
            '*':
              schema:
                type: array
                items:
                  type: string
        '200':
          description: Expected response to a valid request
          content:
            '*':
              schema:
                $ref: "#/components/schemas/PartTo"
    post:
      summary: Define a part to
      operationId: partto:post
      tags:
      - partto 
      requestBody:
        description: describe part to
        content:
          '*':
            schema:
              required:
              - part_to
              - tasks
              type: object
              properties:
                part_to:
                  type: object
                  required:
                  - name
                  - depends
                  properties:
                    name:
                      type: string
                    depends:
                      type: array
                      items:
                        type: string
                tasks:
                  type: array
                  items:
                    $ref: "#/components/schemas/TaskDefinition"
      responses:
        '500':
          description: a backend bug
          content:
            '*':
              schema:
                type: string
        '400':
          description: a frontend bug
          content:
            '*':
              schema:
                type: array
                items:
                  type: string
        '200':
          description: Expected response to a valid request
          content:
            '*':
              schema:
                type: object
                required:
                - partTo
                - message
                properties:
                  partTo:
                    type: string
                    format: PartToId
                  message:
                    type: string
  /api/run/:
    post:
      summary: Start a run
      operationId: run:post
      tags:
      - run
      requestBody:
        description: List of unique part to titles to run
        required: true
        content:
          '*':
            schema:
              type: object
              required:
                - partTo
              properties:
                partTo:
                  type: array
                  items:
                    type: string
                    format: PartToId
                  minItems: 1
      responses:
        '500':
          description: a backend bug
          content:
            '*':
              schema:
                type: string
        '400':
          description: a frontend bug
          content:
            '*':
              schema:
                type: array
                items:
                  type: string
        '200':
          description: Expected response to a valid request
          content:
            '*':
              schema:
                $ref: "#/components/schemas/RunState"
components:
  schemas:
    PartTo:
      type: object
      required:
      - name
      - tasks
      properties:
        name:
          type: string
        tasks:
          type: array
          items:
            type: string
            format: TaskDefinitionId
    TaskDefinition:
      required:
      - duration
      - description
      - name
      type: object
      properties:
        name:
          type: string
        duration:
          type: number
          format: duration
        description:
          type: string
        depends:
          type: array
          items:
            type: string
        engagement:
          type: number
    RunState:
      required:
      - runState
      - report
      - complete
      - duties
      - tasks
      type: object
      properties:
        runState:
          type: string
          format: RunStateId
        report:
          type: string
          format: date-time
        complete:
          type: string
          format: date-time
        duties:
          type: array
          items:
            type: string
            format: TaskDefinitionId
        tasks:
          type: array
          items:
            type: string
            format: TaskDefinitionId
